

name: Python application

on:
  workflow_dispatch:
    inputs:
      name:
        description: "sample description"

jobs:
  test_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3

    - name: Test step
      run: |
        print(${{ github.event.inputs.name }})
